### ISSUE TITLE
Uncaught Error: Cannot find module './atp-view'

### ISSUE THREAD

**Issue by MissHajar** [VadimDor/terminalix#1]
Tried to install this package from Atom UI (Windows 7 x64 - atom 1.22.0) and I got this error:

Uncaught Error: Cannot find module './atp-view'
..\.atom\packages\terminalix\lib\atp-utils.coffee:36
Hide Stack Trace
Error: Cannot find module './atp-view'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (..\AppData\Local\atom\app-1.22.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (..\AppData\Local\atom\app-1.22.0\resources\app\src\module-cache.js:354:58)
    at Module.require (file:///../AppData/Local/atom/app-1.22.0/resources/app.asar/static/index.js:40:43)
    at require (..\AppData\Local\atom\app-1.22.0\resources\app\src\native-compile-cache.js:66:33)
    at global.include (file:///../.atom/packages/terminalix/lib/atp-utils.coffee:25:9)
    at Object.<anonymous> (file:///../.atom/packages/terminalix/lib/atp-panel.coffee:10:17)
    at Object.<anonymous> (file:///../.atom/packages/terminalix/lib/atp-panel.coffee:1:1)
    at Object.<anonymous> (file:///../.atom/packages/terminalix/lib/atp-panel.coffee:1:1)
    at Module.get_Module._compile (..\AppData\Local\atom\app-1.22.0\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .coffee] (..\AppData\Local\atom\app-1.22.0\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///../AppData/Local/atom/app-1.22.0/resources/app.asar/static/index.js:47:45)
    at require (..\AppData\Local\atom\app-1.22.0\resources\app\src\native-compile-cache.js:66:33)
    at global.include (file:///../.atom/packages/terminalix/lib/atp-utils.coffee:25:9)
    at Object.<anonymous> (file:///../.atom/packages/terminalix/lib/atp.coffee:12:12)
    at Object.<anonymous> (file:///../.atom/packages/terminalix/lib/atp.coffee:1:1)
    at Object.<anonymous> (file:///../.atom/packages/terminalix/lib/atp.coffee:1:1)
    at Module.get_Module._compile (..\AppData\Local\atom\app-1.22.0\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .coffee] (..\AppData\Local\atom\app-1.22.0\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///../AppData/Local/atom/app-1.22.0/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (..\AppData\Local\atom\app-1.22.0\resources\app\static\<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (..\AppData\Local\atom\app-1.22.0\resources\app\src\package.js:903:35)
    at Package.module.exports.Package.activateConfig (..\AppData\Local\atom\app-1.22.0\resources\app\src\package.js:301:18)
    at PackageManager.module.exports.PackageManager.packageHasSettings (..\AppData\Local\atom\app-1.22.0\resources\app\node_modules\settings-view\lib\package-manager.js:68:20)
    at PackageCard.hasSettings (..\AppData\Local\atom\app-1.22.0\resources\app\node_modules\settings-view\lib\package-card.js:793:40)
    at PackageCard.updateSettingsState (..\AppData\Local\atom\app-1.22.0\resources\app\node_modules\settings-view\lib\package-card.js:438:22)
    at PackageCard.updateInterfaceState (..\AppData\Local\atom\app-1.22.0\resources\app\node_modules\settings-view\lib\package-card.js:430:18)
    at ..\AppData\Local\atom\app-1.22.0\resources\app\node_modules\settings-view\lib\package-card.js:727:22
    at ..\AppData\Local\atom\app-1.22.0\resources\app\node_modules\settings-view\lib\package-card.js:810:17
    at Function.module.exports.Emitter.simpleDispatch (..\AppData\Local\atom\app-1.22.0\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (..\AppData\Local\atom\app-1.22.0\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (..\AppData\Local\atom\app-1.22.0\resources\app\node_modules\settings-view\lib\package-manager.js:703:33)
    at ..\AppData\Local\atom\app-1.22.0\resources\app\node_modules\settings-view\lib\package-manager.js:542:32
    at exit (..\AppData\Local\atom\app-1.22.0\resources\app\node_modules\settings-view\lib\package-manager.js:128:22)
    at triggerExitCallback (..\AppData\Local\atom\app-1.22.0\resources\app\src\buffered-process.js:338:17)
    at ..\AppData\Local\atom\app-1.22.0\resources\app\src\buffered-process.js:359:17
    at Socket.<anonymous> (..\AppData\Local\atom\app-1.22.0\resources\app\src\buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

**Comment by emeric-martineau** [comment]
`lib/apt-view.coffee` missing in package.

Download https://raw.githubusercontent.com/VadimDor/terminalix/master/lib/atp-view.coffee to lib folder

then
```
npm install ssh2-exec ssh2-connect find-config js-yaml ssh-exec-plus
```

and ...

that's not working :grin:

**Comment by henrikborg** [comment]
Can confirm the issue

Linux Ubuntu 18.04.1
Atom 1.34.0 x64
Electron 2.0.16
Chrome 61.0.3163.100
Node v8.9.3

Uncaught Error: Cannot find module './atp-view'
/home/cyborg/.atom/packages/terminalix/lib/atp-utils.coffee:36
Hide Stack Trace
Error: Cannot find module './atp-view'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/snap/atom/211/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:154667)
    at Module.require (file:///snap/atom/211/usr/share/atom/resources/app.asar/static/index.js:40:43)
    at require (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at global.include (/home/cyborg/.atom/packages/terminalix/lib/atp-utils.coffee:25:9)
    at Object.<anonymous> (/home/cyborg/.atom/packages/terminalix/lib/atp-panel.coffee:10:17)
    at Object.<anonymous> (/home/cyborg/.atom/packages/terminalix/lib/atp-panel.coffee:1:1)
    at Object.<anonymous> (/home/cyborg/.atom/packages/terminalix/lib/atp-panel.coffee:1:1)
    at Module.get_Module._compile (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///snap/atom/211/usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at global.include (/home/cyborg/.atom/packages/terminalix/lib/atp-utils.coffee:25:9)
    at Object.<anonymous> (/home/cyborg/.atom/packages/terminalix/lib/atp.coffee:12:12)
    at Object.<anonymous> (/home/cyborg/.atom/packages/terminalix/lib/atp.coffee:1:1)
    at Object.<anonymous> (/home/cyborg/.atom/packages/terminalix/lib/atp.coffee:1:1)
    at Module.get_Module._compile (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///snap/atom/211/usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:1:639511)
    at Package.requireMainModule (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:2932767)
    at Package.activateConfig (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:2922126)
    at PackageManager.t.exports.PackageManager.packageHasSettings (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:910487)
    at PackageCard.hasSettings (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:2947350)
    at PackageCard.updateSettingsState (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:2937630)
    at PackageCard.updateInterfaceState (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:2937453)
    at /snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:2945583
    at /snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:2947601
    at Function.simpleDispatch (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:1190133)
    at Emitter.emit (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:1191574)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:919667)
    at /snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:917076
    at r (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:911606)
    at o (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:1037724)
    at t.bufferStream (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:1037878)
    at Socket.e.on (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:1036480)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
The error was thrown from the terminalix package. This issue has already been reported.
