### ISSUE TITLE
Uncaught Error: Cannot find module './atp-view'Require stack:- $ATOM_HOME/packages/terminalix/l...

### ISSUE THREAD

**Issue by karthick-kk** [VadimDor/terminalix#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: "Arch Linux"
**Thrown From**: [terminalix](https://github.com/VadimDor/terminalix) package 4.5.0

### Stack Trace

Uncaught Error: Cannot find module './atp-view'
Require stack:
- /home/karthick-k/.atom/packages/terminalix/lib/atp-utils.coffee
- /home/karthick-k/.atom/packages/terminalix/lib/atp.coffee
- /usr/lib/atom/src/package.js
- /usr/lib/atom/src/package-manager.js
- /usr/lib/atom/src/atom-environment.js
- /usr/lib/atom/src/initialize-application-window.js
- /usr/lib/atom/static/index.html

```
At /home/karthick-k/.atom/packages/terminalix/lib/atp-utils.coffee:36

Error: Cannot find module './atp-view'
Require stack:
- /home/karthick-k/.atom/packages/terminalix/lib/atp-utils.coffee
- /home/karthick-k/.atom/packages/terminalix/lib/atp.coffee
- /usr/lib/atom/src/package.js
- /usr/lib/atom/src/package-manager.js
- /usr/lib/atom/src/atom-environment.js
- /usr/lib/atom/src/initialize-application-window.js
- /usr/lib/atom/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (/usr/lib/electron6/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:336:28)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at global.include (/packages/terminalix/lib/atp-utils.coffee:25:9)
    at /packages/terminalix/lib/atp-panel.coffee:10:17)
    at /packages/terminalix/lib/atp-panel.coffee:1:1)
    at /packages/terminalix/lib/atp-panel.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at global.include (/packages/terminalix/lib/atp-utils.coffee:25:9)
    at /packages/terminalix/lib/atp.coffee:12:12)
    at /packages/terminalix/lib/atp.coffee:1:1)
    at /packages/terminalix/lib/atp.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Package.requireMainModule (/usr/lib/atom/src/package.js:907:27)
    at Package.activateConfig (/usr/lib/atom/src/package.js:291:10)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:54:14)
    at PackageCard.hasSettings (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:795:34)
    at PackageCard.updateSettingsState (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:441:16)
    at PackageCard.updateInterfaceState (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:433:12)
    at /usr/lib/atom/node_modules/settings-view/lib/package-card.js:729:16
    at /usr/lib/atom/node_modules/settings-view/lib/package-card.js:812:11
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:662:27)
    at /usr/lib/atom/node_modules/settings-view/lib/package-manager.js:484:26
    at exit (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:280:9)
    at /usr/lib/atom/src/buffered-process.js:301:9
    at Socket.<anonymous> (/usr/lib/atom/src/buffered-process.js:169:7)
    at Socket.emit (events.js:205:15)
    at Pipe.<anonymous> (net.js:586:12)
```

### Commands

```
     -9:34.7.0 settings-view:open (atom-pane.pane.active)
```

### Non-Core Packages

```
git-plus 8.7.1 
terminalix 4.5.0 
```

**Comment by Cerzal** [comment]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description



### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**



**Actual behavior:**



### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [terminalix](https://github.com/VadimDor/terminalix) package 4.5.0


### Stack Trace

Uncaught Error: Cannot find module './atp-view'
Require stack:
- C:\Users\Максим\.atom\packages\terminalix\lib\atp-utils.coffee
- C:\Users\Максим\.atom\packages\terminalix\lib\atp.coffee
- C:\Users\Максим\AppData\Local\atom\app-1.60.0\resources\app.asar\static\index.html

```
At C:\Users\Максим\.atom\packages\terminalix\lib\atp-utils.coffee:36

Error: Cannot find module './atp-view'
Require stack:
- C:\Users\Максим\.atom\packages\terminalix\lib\atp-utils.coffee
- C:\Users\Максим\.atom\packages\terminalix\lib\atp.coffee
- C:\Users\Максим\AppData\Local\atom\app-1.60.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:157942)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149229)
    at global.include (/packages/terminalix/lib/atp-utils.coffee:25:9)
    at /packages/terminalix/lib/atp-panel.coffee:10:17)
    at /packages/terminalix/lib/atp-panel.coffee:1:1)
    at /packages/terminalix/lib/atp-panel.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149913)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149229)
    at global.include (/packages/terminalix/lib/atp-utils.coffee:25:9)
    at /packages/terminalix/lib/atp.coffee:12:12)
    at /packages/terminalix/lib/atp.coffee:1:1)
    at /packages/terminalix/lib/atp.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149913)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:1175135)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:3543231)
    at Package.activateConfig (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:3532534)
    at PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:909286)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:2709249)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:2699517)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:2699340)
    at ~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:2707482
    at ~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:2709500
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1187666)
    at Emitter.emit (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1189107)
    at PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:918743)
    at ~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:915875
    at r (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:910405)
    at n (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:1174458)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:1174664)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
```

### Non-Core Packages

```
terminalix 4.5.0 
```

### Additional Information
